import {api,captureTab} from './shared.js';
const status=document.querySelector('#status');let page,tab;
try{[tab]=await chrome.tabs.query({active:true,currentWindow:true});page=await captureTab(tab.id);document.querySelector('#title').value=page.title;document.querySelector('#content').value=page.selection||page.description;const {entities}=await api('/entities?kind=board');for(const board of entities){const option=document.createElement('option');option.value=board.id;option.textContent=board.title;document.querySelector('#board').append(option);}const {lastBoard}=await chrome.storage.local.get('lastBoard');document.querySelector('#board').value=lastBoard||'';if(new URL(page.url).hostname.endsWith('instagram.com')&&page.url.includes('/saved'))document.querySelector('#collection').hidden=false;}catch(error){status.textContent=error.message;}
document.querySelector('#settings').addEventListener('click',()=>chrome.runtime.openOptionsPage());
document.querySelector('#capture').addEventListener('submit',async event=>{
 event.preventDefault();const button=document.querySelector('#save');button.disabled=true;status.textContent='Saving…';
 try{const boardId=document.querySelector('#board').value;const {entity}=await api('/entities',{kind:'item',title:document.querySelector('#title').value,content:document.querySelector('#content').value||page.content,data:{type:page.selection?'highlight':'link',url:page.url,source:'Grove Capture',capturedAt:new Date().toISOString(),articleText:page.content},tags:document.querySelector('#tags').value.split(',').map(x=>x.trim()).filter(Boolean)});
  if(boardId){const {entity:board}=await api('/entities/'+boardId);const c=await chrome.storage.local.get(['groveUrl','groveToken','groveWorkspace']);const response=await fetch(c.groveUrl+'/api/entities/'+boardId,{method:'PATCH',headers:{Authorization:'Bearer '+c.groveToken,'X-Workspace-Id':c.groveWorkspace,'Content-Type':'application/json'},body:JSON.stringify({version:board.version,data:{...board.data,placements:[...(board.data.placements||[]),{id:entity.id,x:0,y:0}]}})});if(!response.ok)throw new Error('Saved to Library; the board changed. Add the item to the board in Grove.');await chrome.storage.local.set({lastBoard:boardId});}
  status.textContent='Saved. Your idea is now in Grove.';
 }catch(error){status.textContent=error.message;}finally{button.disabled=false;}
});
document.querySelector('#collection').addEventListener('click',async()=>{
 try{status.textContent='Reading visible saved posts…';const [{result:links}]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>[...new Set([...document.querySelectorAll('a[href*="/p/"],a[href*="/reel/"]')].map(a=>a.href))].slice(0,100)});let count=0;for(const url of links){await api('/entities',{kind:'item',title:'Instagram saved post',content:'Captured from your visible saved collection.',tags:['instagram-saves'],data:{type:'link',url,source:'Grove Capture',collection:document.title}});count++;}status.textContent=`Captured ${count} visible posts. Scroll the collection to load other posts before capturing again. Bulk background sync is not enabled.`;}catch(error){status.textContent=error.message;}
});
