import type { ConnectorDefinition, WorkflowTemplate } from '../shared/types.js';

export const workflows: WorkflowTemplate[] = [
  {id:'weekly-strategist',title:'Weekly Strategist',description:'Turn this week’s evidence into one clear creative direction.',icon:'Compass',category:'Strategy',duration:'2–4 min',inputs:['Audience and niche','Goal for the week','Sources to consider'],steps:['Review your recent results','Find patterns in saved market evidence','Write three plays and one weekly bet'],prompt:'Create a dated weekly strategy memo. Separate owned performance from market research. Grade the previous weekly bet only if a prior memo and actual results exist. Identify up to three patterns, each with evidence from distinct creators; fewer if evidence is limited. Give exactly three actionable plays with hooks and one weekly bet with a measurable success criterion. State missing metrics and source limitations. Never invent recent posts or outcomes.'},
  {id:'head-of-content',title:'Head of Content',description:'Build a considered weekly slate, ready for your review.',icon:'CalendarDays',category:'Planning',duration:'3–5 min',inputs:['Channels and cadence','This week’s priorities','Writing voice'],steps:['Read strategy and prior performance','Plan an evidence-backed slate','Prepare drafts for approval'],prompt:'Act as a head of content. Review saved strategy, prior plans, actual queue and available performance. Plan up to seven posts for the coming week using the user cadence. Link each slot to supplied evidence, include at most one experiment. Write publish-ready draft text in the selected voice but DO NOT publish or approve anything. Save a concise weekly report with draft copy and a change log. Missing inputs should be listed, not invented.'},
  {id:'content-command-center',title:'Content Command Center',description:'Bring analysis, research, planning, and repurposing into one daily brief.',icon:'LayoutDashboard',category:'Operations',duration:'3–5 min',inputs:['Business goals','Priority platforms','Digest focus'],steps:['Read connected performance','Scout evidence and opportunities','Create five station briefs'],prompt:'Create a content command center with five stations: Analyst, Scout, Strategist, Planner, Repurposer. Use actual owned metrics only for Analyst. Scout cites real saved or retrieved posts only. Distinguish unavailable metrics from zero. Produce a compact dashboard memo, an action list and a Telegram-ready digest (save text only, do not send). Repurpose one supplied source when available. Record the snapshot date and concrete input gaps.'},
  {id:'personal-brand-strategist',title:'Personal Brand Strategist',description:'Find a distinctive point of view and turn it into a content system.',icon:'Fingerprint',category:'Brand',duration:'3–5 min',inputs:['Your expertise and story','People you want to help','What you want to be known for'],steps:['Understand your experience','Map relevant evidence','Develop positioning and five first posts'],prompt:'Build an original personal brand strategy based on the supplied interview, source material and real creator evidence. Include positioning, audience needs, origin story, a topic tree, content directions and credible monetization options. Curate up to 8–16 actual supplied reference posts, use fewer if insufficient. Give five original first-post hooks and drafts; retain source references. Ask focused next-interview questions where personal facts are missing. Never manufacture credentials, clients or results.'},
  {id:'idea-engine',title:'Idea Engine',description:'Connect your saved ideas with unexpected formats and useful angles.',icon:'Lightbulb',category:'Ideation',duration:'1–3 min',inputs:['Topic or question','Audience','Sources and inspiration'],steps:['Find connections in your library','Compare market patterns','Generate distinctive, supported ideas'],prompt:'Generate 5–8 distinctive idea cards, or fewer when evidence is insufficient. Each needs at least two legs among personal saved knowledge, documented market evidence, and an outside format. For each: original hook in user voice, angle, why it serves the audience, format, two concrete source references and first execution step. Compare previous three idea runs and existing drafts to avoid repeats. Do not invent market breakouts. Conclude with the strongest idea and explain the selection.'},
];

export const builtInSkills = [
 ['skill-creator','Skill creator','Turn a repeatable task into a portable markdown skill with triggers, steps, constraints and examples.'],
 ['prompt-creator','Prompt creator','Design a clear, testable prompt with role, context, input schema, output shape and failure behavior.'],
 ['x-posts','X posts','Write a concise standalone X post. Preserve facts; lead with a specific observation; fit the chosen account limit.'],
 ['x-threads','X threads','Build a readable numbered thread with a compelling opening, one idea per post and a useful ending.'],
 ['linkedin-posts','LinkedIn posts','Write professional first-person content with a grounded hook, practical insight and restrained formatting.'],
 ['instagram-captions','Instagram captions','Write a concise caption, useful context, accessible image description and relevant optional tags.'],
 ['youtube-titles','YouTube titles','Generate specific title options with an honest curiosity gap, explaining the audience promise.'],
 ['newsletter-writer','Newsletter writer','Draft a newsletter with subject options, personal lead, useful sections and a clear reader takeaway.'],
 ['table-builder','Table builder','Design typed columns and useful rows for the task. Make uncertain values explicit and provide valid JSON.'],
].map(([id,title,prompt])=>({id,title,prompt}));

export const marketplace = [
 ['Personal Brand Strategist','Strategy','Clarify positioning, audience, and a consistent point of view.'],['Daily Post Writer','Writing','Turn one useful observation into a considered daily post.'],['Topic Research','Research','Synthesize a topic using your selected sources.'],['Newsletter Studio','Writing','Draft and refine a newsletter in your voice.'],['Thought Partner','Strategy','Question assumptions and explore a difficult decision.'],['Creator Deep Dive','Research','Study a creator from available evidence.'],['Reels Script Studio','Writing','Develop a short video script with a clear visual hook.'],['Weekly Content Planner','Planning','Organize a sustainable week of content.'],['Weekly Strategist','Strategy','Find one creative bet worth pursuing.'],['YouTube Script Studio','Writing','Outline and write a clear long-form video.'],['Substack Notes Studio','Writing','Develop short, conversational notes for your audience.'],['LinkedIn Post Studio','Writing','Share your professional experience with clarity.'],['X Post Studio','Writing','Make a concise original point.'],['YouTube Title Generator','Writing','Explore honest titles that make a strong promise.'],['X Thread Studio','Writing','Build a coherent thread, one thought at a time.'],['Offer Architect','Strategy','Define a useful offer and the evidence supporting it.'],['Landing Page Studio','Marketing','Shape a page around the customer’s needs.'],['Ad Copywriter','Marketing','Draft testable angles with defensible claims.'],['Ad Research','Research','Compare creative patterns without inventing campaign returns.'],
].map(([title,category,description])=>({id:title.toLowerCase().replaceAll(' ','-'),title,category,description,instructions:`You are an expert ${title.toLowerCase()}. ${description} Use only selected knowledge sources for factual claims, cite their source IDs, and clearly state gaps. Keep the writing original. Never invent results, statistics, personal experiences or customer claims. Prepare changes for human review.`,starters:[`Help me get started with ${title.toLowerCase()}.`]}));

const social = (id:string,name:string,capabilities:string[],description:string,docsUrl:string):ConnectorDefinition=>({id,name,category:'social',capabilities,description,docsUrl,auth:'oauth',fields:[{key:'accessToken',label:'Access token',secret:true},{key:'accountId',label:'Account / page ID'},{key:'refreshToken',label:'Refresh token (optional)',secret:true}]});
const business = (id:string,name:string,docsUrl:string,extra?:ConnectorDefinition['fields']):ConnectorDefinition=>({id,name,category:'business',capabilities:['read','sync'],description:`Connect ${name} to bring authorized business context into your workspace.`,docsUrl,auth:'token',fields:[{key:'apiKey',label:'API key / integration token',secret:true},...(extra||[])]});
export const connectors:ConnectorDefinition[] = [
 social('x','X',['publish','analytics','research'],'Posts, threads, account analytics and authorized search.','https://docs.x.com/'),
 social('linkedin','LinkedIn',['publish','analytics'],'Member or organization posts and approved organization analytics.','https://learn.microsoft.com/linkedin/'),
 social('threads','Threads',['publish','analytics','research'],'Publish text and media with your connected Threads profile.','https://developers.facebook.com/docs/threads/'),
 social('instagram','Instagram',['publish','analytics','messaging'],'Professional accounts, media publishing and opted-in messaging automation.','https://developers.facebook.com/docs/instagram-platform/'),
 social('facebook','Facebook Pages',['publish','analytics'],'Page posts and owned Page insights.','https://developers.facebook.com/docs/pages-api/'),
 social('youtube','YouTube',['publish','analytics','research'],'YouTube Shorts uploads, channel research and authorized analytics.','https://developers.google.com/youtube/v3'),
 social('tiktok','TikTok',['publish','analytics'],'Creator-authorized video publishing and display data.','https://developers.tiktok.com/'),
 {id:'substack',name:'Substack',category:'social',auth:'browser',description:'Capture and open drafts in your signed-in Substack browser. Substack has no public publishing API.',capabilities:['browser-handoff','rss'],docsUrl:'https://substack.com/',fields:[{key:'publicationUrl',label:'Publication URL'}]},
 {id:'youtube-data',name:'YouTube research',category:'research',auth:'token',description:'Search public videos and creator channels using your own YouTube Data API key.',capabilities:['research'],docsUrl:'https://developers.google.com/youtube/v3',fields:[{key:'apiKey',label:'YouTube API key',secret:true}]},
 {id:'meta-ad-library',name:'Meta Ad Library',category:'research',auth:'token',description:'Search the ad transparency data available to your approved Ad Library API token.',capabilities:['ad-research'],docsUrl:'https://www.facebook.com/ads/library/api/',fields:[{key:'accessToken',label:'Ad Library API token',secret:true},{key:'countries',label:'Country codes (comma-separated)',placeholder:'US,CA'}]},
 {id:'tiktok-ads',name:'TikTok ad research',category:'research',auth:'none',description:'Import authorized ad research exports. API access depends on TikTok approval.',capabilities:['import'],docsUrl:'https://ads.tiktok.com/business/creativecenter/'},
 business('notion','Notion','https://developers.notion.com/',[{key:'databaseId',label:'Data source ID (optional)'}]),
 business('stripe','Stripe','https://docs.stripe.com/api'),
 business('kit','Kit','https://developers.kit.com/'),
 business('beehiiv','beehiiv','https://developers.beehiiv.com/',[{key:'publicationId',label:'Publication ID'}]),
 business('klaviyo','Klaviyo','https://developers.klaviyo.com/'),
 business('whop','Whop','https://docs.whop.com/'),
 business('kajabi','Kajabi','https://developers.kajabi.com/',[{key:'siteId',label:'Site ID'}]),
 business('webflow','Webflow','https://developers.webflow.com/'),
 business('circle','Circle','https://api.circle.so/'),
 {id:'readwise',name:'Readwise',category:'research',auth:'token',description:'Import books and highlights from your Readwise account.',capabilities:['sync','highlights'],docsUrl:'https://readwise.io/api_deets',fields:[{key:'apiKey',label:'Readwise access token',secret:true}]},
 {id:'rss',name:'RSS & Substack feeds',category:'research',auth:'none',description:'Subscribe to public RSS or Atom feeds and save new articles.',capabilities:['sync'],docsUrl:'https://www.rssboard.org/rss-specification',fields:[{key:'url',label:'Feed URL'}]},
 {id:'telegram',name:'Telegram',category:'delivery',auth:'token',description:'Deliver a routine digest to a chat you configure. Delivery must be enabled explicitly.',capabilities:['send-digest'],docsUrl:'https://core.telegram.org/bots/api',fields:[{key:'botToken',label:'Bot token',secret:true},{key:'chatId',label:'Destination chat ID'}]},
 {id:'mcp',name:'Remote MCP / Zapier',category:'business',auth:'token',description:'Connect an HTTPS Streamable HTTP MCP server; approve tools individually.',capabilities:['tools'],docsUrl:'https://modelcontextprotocol.io/',fields:[{key:'url',label:'HTTPS server URL'},{key:'apiKey',label:'Bearer token (optional)',secret:true}]},
];
