import {clientRateKey} from './core/rate-limit.js';
import express,{Router,type Request} from 'express';
import rateLimit from 'express-rate-limit';
import {z} from 'zod';
import {randomBytes,createHash} from 'node:crypto';
import {requireAuth,assertScope,TOKEN_SCOPES} from './core/auth.js';
import {query} from './core/db.js';
import {listEntities,getEntity,createEntity,updateEntity,deleteEntity,assertAutomationPermissions} from './core/entities.js';
import {saveFile} from './core/files.js';
import {safeFetch,httpError,constantEqual,hashToken} from './core/security.js';
import {analytics,discover,publicConnection,type StoredConnection} from './integrations.js';
import {generate,resolveSources,semanticSearch} from './ai.js';
import {transitionDraft,queuePublish} from './publishing.js';
import {builtInSkills} from './catalog.js';
import type {EntityKind} from '../shared/types.js';
import {tableTypes,replaceTableColumns} from '../shared/table.js';

type Tool={name:string;description:string;scope:string;schema:z.ZodType<any>;run:(wid:string,args:any,req:Request)=>Promise<any>};
export const toolRegistry:Tool[]=[];
const register=(name:string,description:string,scope:string,schema:z.ZodType<any>,run:Tool['run'])=>toolRegistry.push({name:`grove_${name}`,description,scope,schema,run});
const object=(shape:Record<string,z.ZodType>)=>z.object(shape).strict();
const id=z.uuid(),idSchema=object({id}),searchSchema=object({query:z.string().max(500).default('')});
const list=async(wid:string,kind?:string,queryText?:string)=>listEntities(wid,{kind,q:queryText});
const read=async(wid:string,itemId:string,kind?:string)=>{const e=await getEntity(wid,itemId);if(!e||(kind&&e.kind!==kind))throw httpError(404,'Item not found');return e;};
const w='workspace:write',r='workspace:read';
register('list_workspaces','List the authenticated user’s workspaces. Access tokens remain bound to one workspace.',r,object({}),async(wid,_a,req)=>query('SELECT w.id,w.name,m.role FROM workspaces w JOIN memberships m ON m.workspace_id=w.id WHERE m.user_id=$1 AND ($2::boolean=false OR w.id=$3)',[req.auth!.userId,Boolean(req.auth!.scopes),wid]));
register('list_workspace_items','List accessible items, optionally by kind.',r,object({kind:z.string().optional(),query:z.string().optional()}),(wid,a)=>list(wid,a.kind,a.query));
register('search_workspace_items','Search titles and content in accessible workspace items.',r,searchSchema,(wid,a)=>list(wid,undefined,a.query));
register('find_workspace_items','Find conceptually related accessible items using configured embeddings.','ai:run',searchSchema,(wid,a)=>semanticSearch(wid,a.query));
for(const [name,kind] of [['get_note_markdown','item'],['read_media_card','item'],['read_table','table'],['read_social_post','item'],['read_card','item'],['get_custom_ai','custom-ai']] as const)register(name,`Read an accessible ${kind}.`,r,idSchema,(wid,a)=>read(wid,a.id,kind));
register('read_board','Read a board and its accessible linked cards.',r,idSchema,async(wid,a)=>{const board=await read(wid,a.id,'board'),items=[];for(const p of board.data.placements||[]){try{items.push(await read(wid,p.id));}catch{}}return {board,items};});
register('get_connections','List accessible item relationships.',r,idSchema,async(wid,a)=>{const e=await read(wid,a.id);return Promise.all((e.data.connections||[]).map((i:string)=>getEntity(wid,i)));});
register('list_tags','List workspace tags from accessible items.',r,object({}),async wid=>[...new Set((await list(wid)).flatMap(e=>e.tags))]);
for(const [name,kind] of [['list_chats','chat'],['following_overview','creator-list'],['list_custom_ai','custom-ai'],['list_auto_dm_rules','automation'],['list_schedules','routine']] as const)register(name,`List accessible ${kind} records.`,r,object({}),(wid)=>list(wid,kind));
register('search_creators','Find creators already imported or saved in this workspace.','research:read',searchSchema,(wid,a)=>list(wid,'creator',a.query));
register('resolve_creator','Resolve an imported creator by name or handle; does not fabricate missing profiles.','research:read',searchSchema,async(wid,a)=>({creators:await list(wid,'creator',a.query),source:'workspace'}));
for(const name of ['analyze_creator','analyze_list'])register(name,'Analyze a creator or creator list from accessible saved evidence.','ai:run',idSchema,async(wid,a)=>{const entity=await read(wid,a.id);return generate(wid,{input:`Analyze ${entity.title}. Use only available saved evidence, show gaps.`,sourceIds:[entity.id],action:name});});
register('search_social_content','Search connected research providers and your imported corpus.','research:read',object({query:z.string().max(500),platform:z.string().optional(),mode:z.string().optional()}),(wid,a)=>discover(wid,a));
for(const name of ['search_ads','get_brand_ads','get_brand_list_ads'])register(name,'Search authorized or imported ad research; unavailable corpus remains explicit.','research:read',searchSchema,(wid,a)=>discover(wid,{query:a.query,mode:'ads'}));
for(const [name,type] of [['study_top_titles','video'],['study_top_carousels','carousel'],['search_highlights','highlight'],['search_captures','card']] as const)register(name,`Find saved ${type} material.`,r,searchSchema,async(wid,a)=>(await list(wid,'item',a.query)).filter(e=>e.data.contentType===type||e.data.type===type).sort((a,b)=>(b.data.outlier||0)-(a.data.outlier||0)));
register('save_brands_to_list','Create or update an accessible brand watchlist.',w,object({id:id.optional(),title:z.string().max(200),brandIds:z.array(id).max(100)}),async(wid,a)=>{for(const itemId of a.brandIds)await read(wid,itemId,'brand');return a.id?updateEntity(wid,a.id,{title:a.title,data:{brandIds:a.brandIds}}):createEntity(wid,{kind:'creator-list',title:a.title,data:{brandIds:a.brandIds}});});
register('create_board','Create a board with independently reusable placements.',w,object({title:z.string().min(1).max(500)}),(wid,a)=>createEntity(wid,{kind:'board',title:a.title,data:{view:'grid',placements:[],sections:[]}}));
for(const [name,kind] of [['rename_board','board'],['rename_note','item']] as const)register(name,`Rename an accessible ${kind}.`,w,object({id,title:z.string().min(1).max(500)}),async(wid,a)=>{await read(wid,a.id,kind);return updateEntity(wid,a.id,{title:a.title});});
register('trash_board','Move a board to recoverable trash.',w,idSchema,async(wid,a)=>{await read(wid,a.id,'board');return deleteEntity(wid,a.id);});
for(const name of ['create_note','create_sticky_note'])register(name,'Create an original markdown note.',w,object({title:z.string().max(500),content:z.string().max(200000),tags:z.array(z.string()).optional()}),(wid,a)=>createEntity(wid,{kind:'item',...a,data:{type:name==='create_sticky_note'?'card':'document'}}));
register('update_note','Replace markdown in a note with optimistic version checking.',w,object({id,content:z.string().max(200000),version:z.number().int().positive()}),async(wid,a)=>{await read(wid,a.id,'item');return updateEntity(wid,a.id,{content:a.content,version:a.version});});
register('append_to_note','Append markdown to an existing note.',w,object({id,content:z.string().max(60000)}),async(wid,a)=>{const e=await read(wid,a.id,'item');return updateEntity(wid,a.id,{content:e.content+'\n\n'+a.content,version:e.version});});
register('connect_items','Create a bidirectional relationship between two accessible items.',w,object({fromId:id,toId:id}),async(wid,a)=>{const from=await read(wid,a.fromId),to=await read(wid,a.toId);await updateEntity(wid,from.id,{data:{...from.data,connections:[...new Set([...(from.data.connections||[]),to.id])]}});await updateEntity(wid,to.id,{data:{...to.data,connections:[...new Set([...(to.data.connections||[]),from.id])]}});return {connected:true};});
for(const name of ['save_items_to_board','save_posts_to_board','save_ads_to_board'])register(name,'Place accessible existing items on a board without duplicating the original.',w,object({boardId:id,itemIds:z.array(id).max(100)}),async(wid,a)=>{const board=await read(wid,a.boardId,'board');for(const itemId of a.itemIds)await read(wid,itemId);const placements=[...(board.data.placements||[])];for(const itemId of a.itemIds)if(!placements.some(p=>p.id===itemId))placements.push({id:itemId,x:placements.length%3*320,y:Math.floor(placements.length/3)*240});return updateEntity(wid,board.id,{data:{...board.data,placements}});});
register('save_links_to_board','Capture public links safely and place them on a board.',w,object({boardId:id,links:z.array(z.url()).max(20)}),async(wid,a)=>{const board=await read(wid,a.boardId,'board'),placements=[...(board.data.placements||[])];for(const url of a.links){const result=await safeFetch(url);const content=(await result.text()).replace(/<[^>]*>/g,' ').slice(0,40000);const e=await createEntity(wid,{kind:'item',title:new URL(url).hostname,content,data:{type:'link',url}});placements.push({id:e.id,x:0,y:placements.length*220});}return updateEntity(wid,board.id,{data:{...board.data,placements}});});
const tableColumnSchema=z.object({id:z.string().max(100),name:z.string().max(200),type:z.enum(tableTypes),options:z.array(z.string().max(200)).max(200).optional(),optionColors:z.record(z.string(),z.string().regex(/^#[0-9a-f]{6}$/i)).optional(),sourceColumnId:z.string().max(100).optional()}).strict();
const recurrenceSchema=z.object({frequency:z.enum(['daily','weekday','weekly','monthly','yearly','custom']),interval:z.number().int().min(1).max(1000),unit:z.enum(['day','week','month','year']).optional(),anchor:z.enum(['scheduled','completion']),dateColumnId:z.string().max(100),originDate:z.string().optional()}).strict();
const tableRowSchema=z.object({id:z.string().max(100),cells:z.record(z.string(),z.unknown()),itemId:id.nullable().optional(),relatedItemIds:z.array(id).max(80).optional(),createdAt:z.string().optional(),recurrence:recurrenceSchema.optional()}).strict();
register('create_table','Create a typed table with editable options, colors and live computed properties.',w,object({title:z.string().max(500),columns:z.array(tableColumnSchema).max(100)}),(wid,a)=>createEntity(wid,{kind:'table',title:a.title,data:{columns:a.columns,rows:[],view:'table',tableVersion:2}}));
for(const name of ['add_table_rows','update_table_rows'])register(name,'Add or update typed table rows by stable ID. Linked items and recurrence metadata are retained unless explicitly changed.',w,object({id,rows:z.array(tableRowSchema).max(500),version:z.number().int().positive().optional()}),async(wid,a)=>{const t=await read(wid,a.id,'table'),rows=[...(t.data.rows||[])];for(const row of a.rows){const index=rows.findIndex(r=>r.id===row.id);if(index<0)rows.push({...row,createdAt:row.createdAt||new Date().toISOString()});else rows[index]={...rows[index],...row,cells:{...rows[index].cells,...row.cells},lastCompletion:undefined};}return updateEntity(wid,t.id,{data:{...t.data,rows},version:a.version??t.version});});
register('update_table','Update typed properties, layout or saved view settings with optimistic version checking.',w,object({id,columns:z.array(tableColumnSchema).max(100).optional(),view:z.enum(['grid','table','list','kanban','calendar','gallery']).optional(),viewSettings:z.record(z.string(),z.unknown()).optional(),savedViews:z.array(z.record(z.string(),z.unknown())).max(30).optional(),activeViewId:z.string().max(100).optional(),version:z.number().int().positive().optional()}),async(wid,a)=>{const t=await read(wid,a.id,'table'),{id:_id,version,...changes}=a,next={...t.data,...changes,view:a.view==='grid'?'table':a.view||t.data.view};return updateEntity(wid,t.id,{data:a.columns?replaceTableColumns(next,a.columns):next,version:version??t.version});});
register('update_item_tags','Replace tags on an accessible item.',w,object({id,tags:z.array(z.string().max(60)).max(50)}),(wid,a)=>updateEntity(wid,a.id,{tags:a.tags}));
register('update_schedule','Update an existing routine. Activation requires AI scope; delivery also requires publish scope.',w,object({id,cron:z.string().max(80),timezone:z.string().max(80),enabled:z.boolean()}),async(wid,a,req)=>{const e=await read(wid,a.id,'routine'),patch={data:{...e.data,cron:a.cron,timezone:a.timezone,enabled:a.enabled,nextRunAt:null}};assertAutomationPermissions(req,e,patch);return updateEntity(wid,e.id,patch);});
register('list_scheduled_posts','List drafts and their truthful delivery state.',r,object({}),wid=>list(wid,'draft'));
for(const name of ['prepare_scheduling_media_upload','scheduling_media_multipart','upload_scheduling_media'])register(name,'Upload media from a bounded base64 payload. Larger files use authenticated POST /api/uploads multipart.','files:write',object({name:z.string().max(200),mime:z.string().max(100),base64:z.string().max(1_400_000)}),(wid,a)=>saveFile(wid,{name:a.name,mime:a.mime,buffer:Buffer.from(a.base64,'base64')}));
for(const name of ['create_scheduling_draft','schedule_post'])register(name,'Create an unapproved publishing draft. Approval is a separate user action; this tool never schedules unapproved content.',w,object({title:z.string().max(500),content:z.string().max(60000),platforms:z.array(z.string()).max(8)}),(wid,a)=>createEntity(wid,{kind:'draft',title:a.title,content:a.content,data:{platforms:a.platforms,variants:{},status:'draft'}}));
register('publish_post_now','Publish an already approved draft. Requires explicit confirmation and publish scope.','publish:write',object({id,confirm:z.literal(true)}),(wid,a)=>queuePublish(wid,a.id));
register('update_scheduled_post','Edit draft copy and withdraw existing approval.',w,object({id,content:z.string().max(60000)}),async(wid,a)=>{const e=await read(wid,a.id,'draft');if(['publishing','published'].includes(e.data.status))throw httpError(409,'Duplicate a delivered draft before editing');return updateEntity(wid,e.id,{content:a.content,data:{...e.data,status:'draft',approvalId:null,scheduledAt:null}});});
register('cancel_scheduled_post','Withdraw approval and cancel a queued draft.','publish:write',idSchema,(wid,a)=>transitionDraft(wid,a.id,{status:'draft'}));
register('get_analytics','Read actual connected or imported analytics, with unavailable metrics as null.','analytics:read',object({from:z.string().optional(),to:z.string().optional()}),(wid,a)=>analytics(wid,a.from,a.to));
register('list_analytics_posts','Read owned per-post analytics.','analytics:read',object({}),async wid=>(await analytics(wid)).topPosts);
register('connect_social_accounts','Return the interactive connection page; credentials are never accepted through model-generated tool arguments.',r,object({}),async()=>({url:`${process.env.APP_URL}/connections`,requiresUserAction:true}));
register('create_auto_dm_automation','Create a paused Instagram automation for user review.',w,object({title:z.string().max(200),trigger:z.enum(['comment','dm','story-reply']),keywords:z.array(z.string().max(100)).max(20),message:z.string().max(1000),connectionId:id}),(wid,a)=>createEntity(wid,{kind:'automation',title:a.title,data:{...a,enabled:false}}));
register('create_custom_ai','Create a custom AI with a narrow live knowledge boundary.',w,object({title:z.string().max(200),instructions:z.string().max(30000),sourceIds:z.array(id).max(80).default([]),starters:z.array(z.string()).default([])}),async(wid,a)=>{await resolveSources(wid,a.sourceIds);return createEntity(wid,{kind:'custom-ai',title:a.title,visibility:'private',data:{instructions:a.instructions,sourceIds:a.sourceIds,starters:a.starters}});});
register('update_custom_ai','Update custom AI instructions.',w,object({id,instructions:z.string().max(30000),title:z.string().max(200).optional()}),async(wid,a)=>{const e=await read(wid,a.id,'custom-ai');return updateEntity(wid,e.id,{title:a.title||e.title,data:{...e.data,instructions:a.instructions}});});
register('manage_custom_ai_sources','Replace live knowledge pointers with accessible sources.',w,object({id,sourceIds:z.array(id).max(80)}),async(wid,a)=>{const e=await read(wid,a.id,'custom-ai');await resolveSources(wid,a.sourceIds);return updateEntity(wid,e.id,{data:{...e.data,sourceIds:a.sourceIds}});});
register('delete_custom_ai','Move a custom AI to recoverable trash.',w,idSchema,async(wid,a)=>{await read(wid,a.id,'custom-ai');return deleteEntity(wid,a.id);});
register('get_custom_ai_builder_guide','Read how to build a focused custom assistant.',r,object({}),async()=>({guide:'Define one job, give clear instructions, attach only needed live sources, test with source-specific questions, and add starter prompts. Shared templates omit private source IDs. Schedules run under the creator’s current permissions.'}));
register('read_custom_ai_knowledge','Read only the custom assistant’s attached knowledge.',r,idSchema,async(wid,a)=>(await resolveSources(wid,[],a.id)).sources);
register('search_custom_ai_knowledge','Search only a custom assistant’s attached knowledge.',r,object({id,query:z.string().max(500)}),async(wid,a)=>(await resolveSources(wid,[],a.id)).sources.filter(e=>`${e.title} ${e.content}`.toLowerCase().includes(a.query.toLowerCase())));
register('list_skills','List built-in and accessible user-authored portable skills.',r,object({}),async wid=>({builtIn:builtInSkills,custom:(await list(wid,'item')).filter(e=>e.data.type==='skill')}));
for(const name of ['get_skill','export_skill'])register(name,'Read or export a markdown skill. Skill scripts are never executed.',r,object({id:z.string().max(200)}),async(wid,a)=>{const builtin=builtInSkills.find(s=>s.id===a.id);return builtin?{markdown:`# ${builtin.title}\n\n${builtin.prompt}\n`}:read(wid,a.id,'item');});
register('import_skill','Import a markdown skill as inert user data.',w,object({title:z.string().max(200),markdown:z.string().max(150000)}),(wid,a)=>createEntity(wid,{kind:'item',title:a.title,content:a.markdown,data:{type:'skill',enabled:true}}));

export async function callTool(req:Request,name:string,args:any){
 const normalized=name.replace(/^eden_/,'grove_'),tool=toolRegistry.find(t=>t.name===normalized);if(!tool)throw httpError(404,'Unknown tool');
 assertScope(req,tool.scope);
 if(tool.scope.endsWith(':write')||tool.scope==='ai:run'){if(req.auth!.role==='viewer')throw httpError(403,'Editor access is required');}
 return tool.run(req.auth!.workspaceId,tool.schema.parse(args||{}),req);
}
const origin=()=>process.env.APP_URL||'http://localhost:5173';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const mcpRouter=Router();
const limiter=rateLimit({keyGenerator:clientRateKey,windowMs:60000,limit:60,standardHeaders:'draft-8',legacyHeaders:false});
mcpRouter.use(['/mcp','/oauth','/.well-known'],limiter);
mcpRouter.get('/.well-known/oauth-protected-resource',(_req,res)=>res.json({resource:origin()+'/mcp',authorization_servers:[origin()],scopes_supported:TOKEN_SCOPES,bearer_methods_supported:['header']}));
mcpRouter.get('/.well-known/oauth-protected-resource/mcp',(_req,res)=>res.json({resource:origin()+'/mcp',authorization_servers:[origin()],scopes_supported:TOKEN_SCOPES,bearer_methods_supported:['header']}));
mcpRouter.get('/.well-known/oauth-authorization-server',(_req,res)=>res.json({issuer:origin(),authorization_endpoint:origin()+'/oauth/authorize',token_endpoint:origin()+'/oauth/token',registration_endpoint:origin()+'/oauth/register',response_types_supported:['code'],grant_types_supported:['authorization_code'],code_challenge_methods_supported:['S256'],token_endpoint_auth_methods_supported:['none'],scopes_supported:TOKEN_SCOPES}));
mcpRouter.post('/oauth/register',async(req,res)=>{
 const b=z.object({client_name:z.string().max(150).default('MCP client'),redirect_uris:z.array(z.url()).min(1).max(8)}).parse(req.body);
 for(const uri of b.redirect_uris){const u=new URL(uri);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(u.hostname)))throw httpError(400,'Redirect URLs must use HTTPS or a loopback address');if(u.hash||u.username||u.password)throw httpError(400,'Invalid redirect URL');}
 const clientId=randomBytes(24).toString('base64url');await query('INSERT INTO mcp_clients(id,name,redirect_uris) VALUES($1,$2,$3)',[clientId,b.client_name,JSON.stringify(b.redirect_uris)]);res.status(201).json({client_id:clientId,client_name:b.client_name,redirect_uris:b.redirect_uris,token_endpoint_auth_method:'none',grant_types:['authorization_code'],response_types:['code']});
});
const authorizationSchema=z.object({client_id:z.string().max(200),redirect_uri:z.url(),response_type:z.literal('code'),code_challenge:z.string().regex(/^[A-Za-z0-9_-]{43}$/),code_challenge_method:z.literal('S256'),scope:z.string().max(500).default('workspace:read'),state:z.string().max(1000).optional()});
async function validAuthorization(input:any){const b=authorizationSchema.parse(input),[client]=await query<any>('SELECT * FROM mcp_clients WHERE id=$1',[b.client_id]);if(!client||!client.redirect_uris.includes(b.redirect_uri))throw httpError(400,'Unknown OAuth client or redirect URL');const scopes=b.scope.split(' ').filter(Boolean);if(scopes.some(s=>!(TOKEN_SCOPES as readonly string[]).includes(s)))throw httpError(400,'Unsupported scope');return {b,client,scopes};}
mcpRouter.get('/oauth/authorize',requireAuth,async(req,res)=>{if(req.auth!.scopes)throw httpError(403,'Sign in with a browser to authorize a client');const {b,client,scopes}=await validAuthorization(req.query);res.type('html').send(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connect to Grove</title></head><body style="font:16px system-ui;background:#171b19;color:#f4f4f0;padding:8vw;max-width:680px"><h1>Connect ${esc(client.name)} to Grove</h1><p>This client is requesting these permissions in your selected workspace:</p><ul>${scopes.map(s=>`<li>${esc(s)}</li>`).join('')}</ul><p>Only items you can access will be available. Revoke access later in Settings.</p><form method="post" action="/oauth/authorize">${Object.entries(b).map(([k,v])=>`<input type="hidden" name="${esc(k)}" value="${esc(v||'')}">`).join('')}<input type="hidden" name="csrf" value="${esc(req.csrfToken||'')}"><button type="submit" name="decision" value="allow">Authorize</button> <button type="submit" name="decision" value="deny">Cancel</button></form></body></html>`);});
mcpRouter.post('/oauth/authorize',express.urlencoded({extended:false,limit:'20kb'}),requireAuth,async(req,res)=>{if(req.auth!.scopes||!req.csrfToken||!constantEqual(req.body.csrf||'',req.csrfToken))throw httpError(403,'Invalid authorization request');if(req.get('origin')&&req.get('origin')!==origin())throw httpError(403,'Invalid origin');const {b,scopes}=await validAuthorization(req.body),redirect=new URL(b.redirect_uri);if(b.state)redirect.searchParams.set('state',b.state);if(req.body.decision!=='allow'){redirect.searchParams.set('error','access_denied');res.redirect(redirect.toString());return;}if(req.auth!.role==='viewer'&&scopes.some(s=>s.endsWith(':write')||s==='ai:run'))throw httpError(403,'Your workspace role cannot grant these permissions');const code=randomBytes(32).toString('base64url');await query("INSERT INTO mcp_codes(code_hash,client_id,redirect_uri,challenge,user_id,workspace_id,scopes,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,now()+interval '5 minutes')",[hashToken(code),b.client_id,b.redirect_uri,b.code_challenge,req.auth!.userId,req.auth!.workspaceId,JSON.stringify(scopes)]);redirect.searchParams.set('code',code);res.redirect(redirect.toString());});
mcpRouter.post('/oauth/token',express.urlencoded({extended:false,limit:'20kb'}),async(req,res)=>{const b=z.object({grant_type:z.literal('authorization_code'),code:z.string().max(200),code_verifier:z.string().min(43).max(128),client_id:z.string().max(200),redirect_uri:z.url()}).parse(req.body);const challenge=createHash('sha256').update(b.code_verifier).digest('base64url');const [code]=await query<any>('DELETE FROM mcp_codes WHERE code_hash=$1 AND client_id=$2 AND redirect_uri=$3 AND challenge=$4 AND expires_at>now() RETURNING *',[hashToken(b.code),b.client_id,b.redirect_uri,challenge]);if(!code)throw httpError(400,'Authorization code is invalid or expired','invalid_grant');const [member]=await query<any>('SELECT role FROM memberships WHERE workspace_id=$1 AND user_id=$2',[code.workspace_id,code.user_id]);if(!member)throw httpError(403,'Workspace access was revoked');const token='grove_'+randomBytes(36).toString('base64url');await query('INSERT INTO api_tokens(workspace_id,user_id,name,token_hash,scopes) VALUES($1,$2,$3,$4,$5)',[code.workspace_id,code.user_id,`MCP: ${b.client_id.slice(0,12)}`,hashToken(token),JSON.stringify(code.scopes)]);res.setHeader('Cache-Control','no-store');res.json({access_token:token,token_type:'Bearer',scope:code.scopes.join(' ')});});
mcpRouter.all('/mcp',(req,res,next)=>{if(req.get('origin')&&req.get('origin')!==origin())return res.status(403).json({error:'Origin not allowed'});if(!req.get('authorization')?.startsWith('Bearer ')){res.setHeader('WWW-Authenticate',`Bearer resource_metadata="${origin()}/.well-known/oauth-protected-resource"`);return res.status(401).json({error:'Use a scoped Grove token or authorize via OAuth'});}next();},requireAuth);
mcpRouter.get('/mcp',(_req,res)=>res.status(405).setHeader('Allow','POST').end());
mcpRouter.delete('/mcp',(_req,res)=>res.status(204).end());
mcpRouter.post('/mcp',async(req,res)=>{
 const body=z.object({jsonrpc:z.literal('2.0'),id:z.union([z.string(),z.number(),z.null()]).optional(),method:z.string(),params:z.any().optional()}).parse(req.body);
 if(body.id===undefined){res.status(202).end();return;}
 try{
  let result:any;
  if(body.method==='initialize')result={protocolVersion:'2025-03-26',capabilities:{tools:{listChanged:false}},serverInfo:{name:'Grove',version:'0.1.0'},instructions:'Grove is a private creator workspace. Read tool descriptions and scopes. Draft creation never authorizes publishing.'};
  else if(body.method==='ping')result={};
  else if(body.method==='tools/list')result={tools:toolRegistry.map(t=>({name:t.name,description:t.description,inputSchema:z.toJSONSchema(t.schema),annotations:{readOnlyHint:t.scope.endsWith(':read'),destructiveHint:t.name.includes('trash')||t.name.includes('delete'),openWorldHint:['ai:run','research:read','publish:write'].includes(t.scope)}}))};
  else if(body.method==='tools/call'){
   try{const output=await callTool(req,body.params?.name,body.params?.arguments);result={content:[{type:'text',text:JSON.stringify(output)}],structuredContent:{ok:true,result:output},isError:false};}
   catch(error:any){result={content:[{type:'text',text:JSON.stringify({ok:false,status:error.status||400,message:error.message})}],isError:true};}
  }else {res.json({jsonrpc:'2.0',id:body.id,error:{code:-32601,message:'Method not found'}});return;}
  res.json({jsonrpc:'2.0',id:body.id,result});
 }catch(error:any){res.json({jsonrpc:'2.0',id:body.id,error:{code:-32602,message:error.message}});}
});
