import { useState } from 'react';
import { Grid2X2, List, Network, Plus, Download, Upload, Star, BookOpen, SlidersHorizontal, Sparkles, Link2, FileText, Highlighter, Rss } from 'lucide-react';
import { useWorkspace } from '../store';
import { api, post, download } from '../api';
import { Button, IconButton, PageHeader, Tabs, Empty, SearchBox, Modal, Field, Input, Badge, ErrorNotice, timeAgo } from '../components/ui';
import { KnowledgeGraph } from '../components/KnowledgeGraph';
import { ItemCard, ItemIcon, CreateModal } from '../components/items';
import type { Entity, Preferences } from '../../shared/types';
export function Library() {
 const app = useWorkspace(); const [query, setQuery] = useState(''); const {tab, view, tag, platform, source} = app.preferences.library; const favorites = new Set(app.preferences.pinnedIds); const setFilters = (library: Partial<Preferences['library']>) => { void app.run(() => app.savePreferences({library})); }; const setTab = (tab: string) => setFilters({tab: tab as Preferences['library']['tab']}); const setView = (view: string) => setFilters({view: view as Preferences['library']['view']}); const setTag = (tag: string) => setFilters({tag}); const [create, setCreate] = useState(false); const [importing, setImporting] = useState(false); const [feed, setFeed] = useState(false); const [semantic, setSemantic] = useState<Entity[] | null>(null); const [busy, setBusy] = useState(false);
 const items = app.entities.filter(e => ['item', 'table', 'voice'].includes(e.kind)); const allTags = [...new Set(items.flatMap(e => e.tags))];
 const platformOf = (e: Entity) => String(e.data.platform || ''); const sourceOf = (e: Entity) => { try { return e.data.url ? new URL(e.data.url).hostname.replace(/^www\./, '') : String(e.data.captureSource || e.data.source || ''); } catch { return ''; } }; const allPlatforms = [...new Set(items.map(platformOf).filter(Boolean))].sort(); const allSources = [...new Set(items.map(sourceOf).filter(Boolean))].sort();
 const filtered = (semantic || items).filter(e => (semantic || `${e.title} ${e.content} ${e.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())) && (!tag || e.tags.includes(tag)) && (!platform || platformOf(e) === platform) && (!source || sourceOf(e) === source) && (tab === 'all' || tab === 'favorites' && favorites.has(e.id) || tab === 'reading' && e.data.readLater || tab === 'highlights' && e.data.type === 'highlight' || tab === 'documents' && ['document', 'card'].includes(e.data.type) || tab === 'media' && ['file', 'image', 'video', 'audio', 'pdf'].includes(e.data.type)));
 async function semanticSearch() { setBusy(true); await app.run(async () => { const r = await post('/search/semantic', { query }); setSemantic(r.entities || r.results?.map((x: any) => x.entity || x) || []); }); setBusy(false); }
 return <><PageHeader eyebrow="YOUR SECOND BRAIN" title="Library" description="Everything you've collected. Ready for what comes next."><Button onClick={() => setImporting(true)}><Upload size={15} />Import</Button><Button tone="primary" onClick={() => setCreate(true)}><Plus size={16} />New item</Button></PageHeader>
 <Tabs value={tab} onChange={setTab} items={[{ id: 'all', label: 'Everything', count: items.length }, { id: 'documents', label: 'Notes' }, { id: 'highlights', label: 'Highlights' }, { id: 'reading', label: 'Read later' }, { id: 'favorites', label: 'Favorites' }, { id: 'media', label: 'Files & media' }]} />
 <div className="filter-toolbar"><SearchBox value={query} onChange={q => { setQuery(q); setSemantic(null); }} placeholder="Search your notes, links, highlights…" /><Button tone="ghost" busy={busy} onClick={() => void semanticSearch()} disabled={!query.trim()}><Sparkles size={14} />By meaning</Button><select aria-label="Filter by tag" value={tag} onChange={e => setTag(e.target.value)}><option value="">All tags</option>{allTags.map(t => <option key={t}>{t}</option>)}</select><select aria-label="Filter by platform" value={platform} onChange={e => setFilters({platform: e.target.value})}><option value="">All platforms</option>{allPlatforms.map(value => <option key={value}>{value}</option>)}</select><select aria-label="Filter by source" value={source} onChange={e => setFilters({source: e.target.value})}><option value="">All sources</option>{allSources.map(value => <option key={value}>{value}</option>)}</select><div className="spacer" /><IconButton label="RSS feeds" onClick={() => setFeed(true)}><Rss size={17} /></IconButton><IconButton label="Export library" onClick={() => void app.run(() => download('/export?format=json', 'grove-workspace.json'))}><Download size={17} /></IconButton><div className="segmented">{[{ id: 'grid', icon: Grid2X2 }, { id: 'list', icon: List }, { id: 'graph', icon: Network }].map(v => <IconButton key={v.id} label={`${v.id} view`} className={view === v.id ? 'active' : ''} onClick={() => setView(v.id)}><v.icon size={16} /></IconButton>)}</div></div>
 {(tag || platform || source) && <div className="subtle-banner">Filters are saved for your account.<button onClick={() => setFilters({tag: '', platform: '', source: ''})}>Clear filters</button></div>}
 {semantic && <div className="subtle-banner"><Sparkles size={15} />Showing {filtered.length} matches by meaning.<button onClick={() => setSemantic(null)}>Clear</button></div>}
 {!filtered.length ? <Empty icon={<BookOpen size={30} />} title={query || tag ? 'Nothing here just yet' : 'A home for everything worth keeping'} description={query ? 'Try a different phrase, or clear your filters.' : 'Save a link, write down a thought, or bring your notes with you. Your library grows from there.'} action={<Button tone="primary" onClick={() => setCreate(true)}><Plus size={15} />Save your first idea</Button>} /> : view === 'graph' ? <KnowledgeGraph items={filtered} /> : view === 'list' ? <div className="item-list"><div className="list-labels"><span>Name</span><span>Tags</span><span>Updated</span></div>{filtered.map(e => <button key={e.id} className="item-list-row" onClick={() => app.openItem(e.id)}><div><ItemIcon entity={e} /><span>{e.title}</span>{favorites.has(e.id) && <Star size={13} className="starred" />}</div><span>{e.tags.slice(0, 2).map(t => <Badge key={t}>{t}</Badge>)}</span><small>{timeAgo(e.updatedAt)}</small></button>)}</div> : <div className="item-grid">{filtered.map(e => <ItemCard key={e.id} entity={e} />)}</div>}
 {create && <CreateModal onClose={() => setCreate(false)} />}{importing && <ImportModal onClose={() => setImporting(false)} />}{feed && <FeedsModal onClose={() => setFeed(false)} />}</>;
}
export function ImportModal({ onClose }: { onClose: () => void }) { const app = useWorkspace(); const [file, setFile] = useState<File | null>(null); const [format, setFormat] = useState('auto'); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); return <Modal title="Bring your ideas with you" onClose={onClose}><form className="form-stack" onSubmit={async e => { e.preventDefault(); if (!file) return; setBusy(true); setError(''); try { const body = new FormData(); body.append('file', file); body.append('format', format); const r = await api('/imports', { method: 'POST', body }); await app.refresh(); app.notify(`${r.count ?? r.entities?.length ?? 0} items imported`); onClose(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><p className="muted">Import markdown, CSV, JSON, Evernote or HTML exports. Original files stay on your device.</p><Field label="Import format"><select value={format} onChange={e => setFormat(e.target.value)}><option value="auto">Detect automatically</option><option value="markdown">Markdown / Obsidian</option><option value="csv">CSV / Notion table</option><option value="json">Grove JSON</option><option value="enex">Evernote ENEX</option><option value="html">HTML / Apple Notes export</option></select></Field><label className="dropzone"><Upload size={28} /><strong>{file?.name || 'Choose an export file'}</strong><input type="file" required onChange={e => setFile(e.target.files?.[0] || null)} /></label>{error && <ErrorNotice>{error}</ErrorNotice>}<div className="form-actions"><Button onClick={onClose} type="button">Cancel</Button><Button type="submit" tone="primary" busy={busy}>Import into library</Button></div></form></Modal>; }
function FeedsModal({ onClose }: { onClose: () => void }) {
 const app = useWorkspace(); const [url, setUrl] = useState(''); const [title, setTitle] = useState(''); const [busy, setBusy] = useState(false); const feeds = app.connections.filter(c => c.provider === 'rss');
 return <Modal title="Reading subscriptions" onClose={onClose}><div className="form-stack"><p className="muted">Subscribe to public RSS and Atom feeds. New articles save to your library with links to the original source.</p>{feeds.map(f => <div className="setting-row" key={f.id}><div><strong>{f.label || 'RSS feed'}</strong><small>{f.lastSyncAt ? `Synced ${timeAgo(f.lastSyncAt)}` : f.error || f.status}</small></div><Button onClick={() => void app.run(async () => { await post(`/connections/${f.id}/sync`); await app.refresh(); }, 'Feed sync requested')}>Sync</Button><Button onClick={() => void app.run(async () => { await api(`/connections/${f.id}`, { method: 'DELETE' }); await app.refresh(); }, 'Feed removed')}>Remove</Button></div>)}<form className="form-stack" onSubmit={async e => { e.preventDefault(); setBusy(true); await app.run(async () => { const r = await post('/connections/rss', { label: title || new URL(url).hostname, credentials: { url }, config: { autoSync: true } }); await post(`/connections/${r.connection.id}/sync`); await app.refresh(); setUrl(''); setTitle(''); }, 'Feed connected and sync requested'); setBusy(false); }}><Field label="Feed name"><Input value={title} onChange={e => setTitle(e.target.value)} placeholder="My favorite publication" /></Field><Field label="RSS URL"><Input type="url" required value={url} onChange={e => setUrl(e.target.value)} placeholder="https://example.com/feed.xml" /></Field><Button tone="primary" type="submit" busy={busy}><Plus size={15} />Subscribe to feed</Button></form></div></Modal>;
}
