import { useEffect, useState, useRef, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import ReactMarkdown, { defaultUrlTransform } from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { FileText, StickyNote, Link as LinkIcon, Image, File, Video, Star, MoreHorizontal, BookOpen, ArrowUpRight, Highlighter, Download, MessageSquare, History, Trash2, Copy, Share2, Save, Quote, Table2, Layers, Plus, Upload, Check, LockKeyhole, Users, Globe, X, ExternalLink as ExternalIcon } from 'lucide-react';
import type { Entity, EntityInput } from '../../shared/types';
import { useWorkspace } from '../store';
import { api, post, patch, getFileBlob, safeUrl, saveBlob } from '../api';
import { Button, IconButton, Modal, Field, Input, TagsInput, Badge, Tabs, Empty, timeAgo, SearchBox, ErrorNotice, Loading } from './ui';
import { DocumentEditor, documentChange } from './editor/DocumentEditor';
import { DocumentNavigation, documentMarkdown, markdownDocument } from './editor/DocumentNodes';
import { Backlinks } from './editor/RelatedSources';
import { Reader } from './reader/Reader';
import { useReadingState } from './reader/useReadingState';
import { readItemDraft } from './editor/draftRecovery';
export function ItemIcon({ entity, size = 18 }: { entity: Entity; size?: number }) { const type = entity.data.type; const Icon = entity.kind === 'table' ? Table2 : entity.kind === 'board' ? Layers : type === 'card' ? StickyNote : type === 'link' ? LinkIcon : type === 'highlight' ? Highlighter : ['image', 'photo'].includes(type) || String(entity.data.mime || '').startsWith('image') ? Image : type === 'video' ? Video : type === 'file' ? File : FileText; return <Icon size={size} />; }
export function ItemCard({ entity, compact = false, onOpen }: { entity: Entity; compact?: boolean; onOpen?: () => void }) {
 const { openItem, update, run, preferences, pin } = useWorkspace(); const [menu, setMenu] = useState(false); const starred = preferences.pinnedIds.includes(entity.id);
 const imageUrl = safeUrl(entity.data.thumbnail || entity.data.imageUrl);
 return <article className={`item-card ${compact ? 'compact' : ''} type-${entity.data.type || entity.kind}`}>
  <button className="card-main" onClick={onOpen || (() => openItem(entity.id))}>
   {!compact && <div className={`card-preview ${imageUrl ? 'has-image' : ''}`}>{imageUrl ? <img src={imageUrl} loading="lazy" alt="" /> : <>{entity.data.type === 'highlight' && <Quote className="quote-mark" size={26} />}<p>{entity.content?.slice(0, 420) || (entity.kind === 'table' ? `${entity.data.rows?.length || 0} rows · ${entity.data.columns?.length || 0} properties` : entity.data.description || entity.data.url || 'A little room for your next idea.')}</p></>}</div>}
   <div className="card-caption"><span className="item-type-icon"><ItemIcon entity={entity} size={16} /></span><div><h3>{entity.title || 'Untitled'}</h3><span>{entity.data.platform || entity.data.type || entity.kind} <i>·</i> {timeAgo(entity.updatedAt)}</span></div></div>
   {entity.tags.length > 0 && <div className="card-tags">{entity.tags.slice(0, 3).map(t => <span key={t}>{t}</span>)}</div>}
  </button>
  <div className="card-actions"><IconButton label={starred ? 'Remove from favorites' : 'Add to favorites'} className={starred ? 'starred' : ''} onClick={() => void run(() => pin(entity.id, !starred))}><Star size={15} fill={starred ? 'currentColor' : 'none'} /></IconButton><IconButton label="Item actions" onClick={() => setMenu(!menu)}><MoreHorizontal size={16} /></IconButton>{menu && <div className="popover-menu"><button onClick={() => { void run(() => update(entity.id, { data: { ...entity.data, readLater: !entity.data.readLater } }), entity.data.readLater ? 'Removed from reading list' : 'Saved to your reading list'); setMenu(false); }}><BookOpen size={15} />{entity.data.readLater ? 'Mark as read' : 'Read later'}</button><button onClick={() => { openItem(entity.id); setMenu(false); }}><FileText size={15} />Open details</button></div>}</div>
 </article>;
}
export function CreateModal({ onClose, initial = 'document', parentId }: { onClose: () => void; initial?: string; parentId?: string }) {
 const { create, put, notify, openItem, entities, update, preferences, savePreferences } = useWorkspace(); const [destination, setDestination] = useState(parentId || preferences.captureBoardId || ''); const [remember, setRemember] = useState(false); const [type, setType] = useState(initial); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [url, setUrl] = useState(''); const [tags, setTags] = useState<string[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [files, setFiles] = useState<File[]>([]); const captured = useRef<Entity[]>([]); const [hasCaptured, setHasCaptured] = useState(false);
 async function attach(e: Entity) { if (!destination || ['board', 'space'].includes(type)) return; const { entity: board } = await api<{ entity: Entity }>(`/entities/${destination}`); if ((board.data.placements || []).some((p: any) => p.id === e.id)) return; await update(board.id, { version: board.version, data: { ...board.data, placements: [...(board.data.placements || []), { id: e.id, x: 40 + (board.data.placements?.length || 0) * 35, y: 40 }] } }); }
 async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try {
  let entity: Entity | undefined; const captureParent = !['board', 'space'].includes(type) && destination ? destination : undefined;
  if (type === 'upload') { if (!files.length) throw new Error('Choose at least one file.'); for (let index = 0; index < files.length; index++) { entity = captured.current[index]; if (!entity) { const body = new FormData(); body.append('file', files[index]); if (captureParent) body.append('parentId', captureParent); const result = await api<{ entity: Entity }>('/uploads', { method: 'POST', body }); entity = result.entity; captured.current.push(entity); setHasCaptured(true); put(entity); } await attach(entity); } }
  else { entity = captured.current[0]; if (!entity) {
   if (type === 'link') { const result = await post<{ entity: Entity }>('/capture', { url, title: title || undefined, content: content || undefined, tags, parentId: captureParent }); entity = result.entity; put(entity); }
   else { const input: EntityInput = { kind: type === 'board' || type === 'table' || type === 'space' ? type : 'item', title: title || (type === 'board' ? 'Untitled board' : type === 'table' ? 'Untitled table' : 'Untitled note'), content, tags, parentId: captureParent, data: type === 'board' ? { view: 'grid', placements: [], sections: [] } : type === 'table' ? { view: 'table', columns: [{ id: 'name', name: 'Name', type: 'text' }, { id: 'status', name: 'Status', type: 'select', options: ['Idea', 'In progress', 'Done'] }, { id: 'date', name: 'Date', type: 'date' }], rows: [] } : { type } }; entity = await create(input); }
   captured.current.push(entity); setHasCaptured(true);
  } await attach(entity); }
  if (remember && !['board', 'space'].includes(type)) { try { await savePreferences({ captureBoardId: destination || null }); } catch { notify('Your item is saved, but the default capture destination could not be updated.', 'error'); } }
  notify(type === 'upload' ? `${files.length} file${files.length === 1 ? '' : 's'} added to your library` : 'Saved to your workspace'); onClose(); if (entity && !['board', 'space'].includes(entity.kind)) openItem(entity.id);
 } catch (e) { setError(captured.current.length ? `Your captured items are saved. Retry to finish placing them on the board. ${(e as Error).message}` : (e as Error).message); } finally { setBusy(false); } }
 return <Modal title="Make room for an idea" onClose={() => { if (!busy) onClose(); }}><form onSubmit={submit} className="form-stack"><fieldset className="editor-fields form-stack" disabled={busy || hasCaptured}><Tabs value={type} onChange={setType} items={[{ id: 'document', label: 'Note', icon: <FileText size={14} /> }, { id: 'card', label: 'Card', icon: <StickyNote size={14} /> }, { id: 'link', label: 'Link', icon: <LinkIcon size={14} /> }, { id: 'upload', label: 'Upload', icon: <Upload size={14} /> }, { id: 'board', label: 'Board' }, { id: 'table', label: 'Table' }, { id: 'space', label: 'Space' }]} />
 {type === 'upload' ? <label className="dropzone"><Upload size={27} /><strong>Drop files here, or browse</strong><span>Documents, PDFs, images, audio and video</span><input type="file" multiple onChange={e => setFiles(Array.from(e.target.files || []))} />{files.map(f => <span key={f.name} className="file-chip">{f.name} · {(f.size / 1024).toFixed(0)} KB</span>)}</label> : <><Field label={type === 'link' ? 'Title (optional)' : 'Title'}><Input value={title} onChange={e => setTitle(e.target.value)} placeholder={type === 'board' ? 'A project, a curiosity, a collection…' : 'Give it a name…'} autoFocus /></Field>{type === 'link' && <Field label="Source URL"><Input type="url" required value={url} onChange={e => setUrl(e.target.value)} placeholder="https://" /></Field>}{!['board', 'table', 'space'].includes(type) && <Field label={type === 'link' ? 'Your notes (optional)' : 'Your idea'}><textarea value={content} onChange={e => setContent(e.target.value)} rows={5} placeholder="Start anywhere. A sentence is enough." /></Field>}<Field label="Tags"><TagsInput value={tags} onChange={setTags} /></Field></>}
 {!['board', 'space'].includes(type) && <><Field label="Save to"><select aria-label="Capture destination" value={destination} onChange={e => setDestination(e.target.value)}><option value="">Library only</option>{entities.filter(e => e.kind === 'board').map(b => <option key={b.id} value={b.id}>{b.title}</option>)}</select></Field><label className="checkbox-label"><input type="checkbox" checked={remember} onChange={e => setRemember(e.target.checked)} />Use this destination for future captures</label></>}
 </fieldset>{error && <ErrorNotice>{error}</ErrorNotice>}<div className="form-actions"><Button type="button" disabled={busy} onClick={onClose}>{hasCaptured ? 'Close' : 'Cancel'}</Button><Button tone="primary" busy={busy} type="submit"><Plus size={15} />{hasCaptured ? 'Retry board placement' : type === 'upload' ? 'Upload files' : type === 'link' ? 'Save link' : `Create ${type === 'document' ? 'note' : type}`}</Button></div></form></Modal>;
}
export function SourcePicker({ value, onChange, label = 'Connected knowledge' }: { value: string[]; onChange: (v: string[]) => void; label?: string }) { const { entities } = useWorkspace(); const [q, setQ] = useState(''); const candidates = entities.filter(e => ['item', 'board', 'table', 'creator', 'voice'].includes(e.kind) && e.title.toLowerCase().includes(q.toLowerCase())); return <div className="source-picker"><div className="field-label">{label}<Badge>{value.length}</Badge></div><SearchBox value={q} onChange={setQ} placeholder="Find notes, boards, creators…" /><div className="source-options">{candidates.slice(0, 50).map(e => <label key={e.id}><input type="checkbox" checked={value.includes(e.id)} onChange={() => onChange(value.includes(e.id) ? value.filter(id => id !== e.id) : [...value, e.id])} /><ItemIcon entity={e} size={15} /><span>{e.title}</span><small>{e.kind}</small></label>)}{!candidates.length && <p className="muted small">Save a note or source to your library to connect it here.</p>}</div></div>; }
export function Markdown({ children, baseUrl }: { children: string; baseUrl?: string }) {
 const transformUrl = (value: string) => {
  const safe = defaultUrlTransform(value);
  if (!baseUrl || !safe) return safe;
  try { return defaultUrlTransform(new URL(safe, baseUrl).href); } catch { return ''; }
 };
 return <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} urlTransform={transformUrl} components={{ a: props => <a {...props} target="_blank" rel="noopener noreferrer" /> }}>{children}</ReactMarkdown></div>;
}
export function FilePreview({ entity }: { entity: Entity }) { const [url, setUrl] = useState(''); const [error, setError] = useState(''); useEffect(() => { let objectUrl = ''; getFileBlob(entity.id).then(blob => { objectUrl = URL.createObjectURL(blob); setUrl(objectUrl); }).catch(e => setError(e.message)); return () => { if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [entity.id]); const mime = entity.data.mime || entity.data.mimeType || ''; if (error) return <ErrorNotice>{error}</ErrorNotice>; if (!url) return <p className="muted">Opening file…</p>; return mime.startsWith('image') ? <img className="file-preview" src={url} alt={entity.title} /> : mime === 'application/pdf' ? <iframe title={entity.title} className="pdf-preview" src={url} /> : mime.startsWith('audio') ? <audio controls src={url} /> : mime.startsWith('video') ? <video className="file-preview" controls src={url} /> : <a className="button" href={url} download={entity.title}><Download size={16} />Download original file</a>; }
type ItemPermission = 'view' | 'comment' | 'edit' | 'manage';
export interface ItemAccess {
 visibility: 'workspace' | 'private'; createdBy: string | null; permission: ItemPermission;
 grants: { userId: string; name: string; email: string; permission: Exclude<ItemPermission, 'manage'> }[];
 invitations: { id: string; email: string; permission: Exclude<ItemPermission, 'manage'>; expiresAt: string }[];
}
export function ItemEditor({ entity, onClose }: { entity: Entity; onClose: () => void }) {
 const app = useWorkspace(), navigate = useNavigate(), reading = useReadingState(entity.id);
 const draftKey = `grove-item-draft:${app.workspace.id}:${app.session.user.id}:${entity.id}`;
 const [recovery] = useState(() => readItemDraft(draftKey)), [recoveryConflict, setRecoveryConflict] = useState(!!recovery && recovery.version !== entity.version), [recoveryError, setRecoveryError] = useState('');
 const recoveryBlocked = useRef(recoveryConflict);
 const initialDraft = recovery?.draft || entity;
 const [title, setTitle] = useState(initialDraft.title), [content, setContent] = useState(initialDraft.content), [data, setData] = useState(initialDraft.data), [tags, setTags] = useState(initialDraft.tags);
 const currentDraft = useRef({ title, content, data, tags }); currentDraft.current = { title, content, data, tags };
 const [tab, setTab] = useState(() => entity.data.mime || entity.data.mimeType || entity.data.type === 'file' || new URLSearchParams(window.location.search).get('highlight') ? 'read' : 'write'), [busy, setBusy] = useState(false), [saved, setSaved] = useState('All changes saved');
 const [extra, setExtra] = useState<'comments' | 'history' | 'share' | null>(null), [records, setRecords] = useState<any[]>([]), [comment, setComment] = useState('');
 const [access, setAccess] = useState<ItemAccess | null>(null), [accessError, setAccessError] = useState(''), [accessSaving, setAccessSaving] = useState(false);
 const observedDraft = useRef({ title: entity.title, content: entity.content, data: entity.data, tags: entity.tags }), editRevision = useRef(0), version = useRef(recovery?.version ?? entity.version), dirty = useRef(!!recovery);
 const savingTask = useRef<Promise<boolean> | null>(null), saveRef = useRef<() => Promise<boolean>>(async () => true);
 const isFile = !!(data.mime || data.mimeType || data.fileId || data.type === 'file');
 const canEdit = access?.permission === 'edit' || access?.permission === 'manage';
 const canComment = canEdit || access?.permission === 'comment';
 const canCreate = app.workspace.role !== 'viewer' && !app.workspace.itemOnly;
 async function refreshAccess() { const result = await api<ItemAccess>(`/entities/${entity.id}/access`); setAccess(result); setAccessError(''); return result; }
 useEffect(() => { let live = true; api<ItemAccess>(`/entities/${entity.id}/access`).then(result => { if (live) { setAccess(result); if (!['edit', 'manage'].includes(result.permission)) setTab('read'); } }).catch(e => { if (live) setAccessError(e.message); }); return () => { live = false; }; }, [entity.id]);
 function persistDraft() { try { if (dirty.current) localStorage.setItem(draftKey, JSON.stringify({ version: version.current, draft: currentDraft.current, savedAt: new Date().toISOString() })); else localStorage.removeItem(draftKey); setRecoveryError(''); } catch { setRecoveryError('Local draft recovery is unavailable. Keep this item open until its changes are saved.'); } }
 async function save(): Promise<boolean> {
  if (recoveryBlocked.current) return false;
  if (savingTask.current) { const ok = await savingTask.current; return ok && dirty.current ? saveRef.current() : ok; }
  if (!dirty.current) return true;
  const revision = editRevision.current; setBusy(true);
  const task = (async () => { try { const result = await app.update(entity.id, { title, content, tags, data, version: version.current }); version.current = result.version; if (editRevision.current === revision) { dirty.current = false; setSaved('All changes saved'); } persistDraft(); return true; } catch (e) { persistDraft(); setSaved('Could not save — your changes are still here'); app.notify((e as Error).message, 'error'); return false; } finally { setBusy(false); } })();
  savingTask.current = task; const ok = await task; savingTask.current = null; return ok && dirty.current ? saveRef.current() : ok;
 }
 saveRef.current = save;
 const navigationGuard = useRef<() => Promise<boolean>>(async () => true); navigationGuard.current = async () => !accessSaving && await saveRef.current() && await reading.flush();
 useEffect(() => app.registerItemGuard(entity.id, () => navigationGuard.current()), [app.registerItemGuard, entity.id]);
 useEffect(() => { const previous = observedDraft.current; if (previous.title === title && previous.content === content && previous.data === data && previous.tags === tags) return; observedDraft.current = { title, content, data, tags }; ++editRevision.current; dirty.current = true; setSaved('Unsaved changes'); persistDraft(); if (recoveryBlocked.current) return; const timer = setTimeout(() => void saveRef.current(), 1200); return () => clearTimeout(timer); }, [title, content, data, tags]);
 useEffect(() => { const handler = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key === 's') { e.preventDefault(); void saveRef.current(); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);
 const readingDirty = useRef(reading.dirty); readingDirty.current = reading.dirty;
 useEffect(() => { const leave = (event: BeforeUnloadEvent) => { if (dirty.current || readingDirty.current) { persistDraft(); event.preventDefault(); event.returnValue = ''; } }; window.addEventListener('beforeunload', leave); return () => { window.removeEventListener('beforeunload', leave); persistDraft(); if (dirty.current) void saveRef.current(); }; }, [draftKey]);
 function applyEntity(next: Entity) { recoveryBlocked.current = false; setRecoveryConflict(false); version.current = next.version; observedDraft.current = { title: next.title, content: next.content, data: next.data, tags: next.tags }; dirty.current = false; ++editRevision.current; setTitle(next.title); setContent(next.content); setData(next.data); setTags(next.tags); setSaved('All changes saved'); persistDraft(); app.put(next); }
 async function withSavedItem(action: () => Promise<void>) { setAccessSaving(true); try { if (!await saveRef.current()) throw new Error('Save your draft successfully before changing sharing. Your changes are still here.'); await action(); } finally { setAccessSaving(false); } }
 async function changeVisibility(visibility: ItemAccess['visibility']) {
  const result = await patch<{ entity: Entity }>(`/entities/${entity.id}/access`, { visibility }); applyEntity(result.entity);
  if (visibility === 'private' && result.entity.createdBy && result.entity.createdBy !== app.session.user.id) { onClose(); await app.refresh(); app.notify('This item is now private to its owner and invited collaborators.'); return; }
  await refreshAccess(); app.notify('Item visibility updated');
 }
 async function close() { if (!accessSaving && await saveRef.current() && await reading.flush()) onClose(); }
 async function openReference(id: string) { if (accessSaving || !await saveRef.current() || !await reading.flush()) return; const target = app.entities.find(item => item.id === id); if (!target) { app.notify('This source is unavailable.', 'info'); return; } if (target.kind === 'board' || target.kind === 'chat') { app.closeItem(); navigate(target.kind === 'board' ? `/boards/${id}` : `/chat/${id}`); } else app.openItem(id); }
 async function openSourcePassage() { if (!data.sourceId || !await saveRef.current() || !await reading.flush()) return; if (!app.entities.some(item => item.id === data.sourceId)) { app.notify('This source is unavailable. Your saved highlight is still here.', 'info'); return; } navigate(`/library?open=${encodeURIComponent(data.sourceId)}&highlight=${entity.id}`); app.openItem(data.sourceId); }
 async function loadExtra(type: 'comments' | 'history' | 'share') { setExtra(extra === type ? null : type); setRecords([]); if (type !== 'share') await app.run(async () => { const r = await api(`/entities/${entity.id}/${type}`); setRecords(r[type] || r.versions || r.history || []); }); }
 const tabItems = [...(canEdit && !isFile ? [{ id: 'write', label: 'Write' }] : []), { id: 'read', label: 'Reader' }, ...(canEdit && !isFile ? [{ id: 'markdown', label: 'Markdown' }] : []), ...(canEdit ? [{ id: 'related', label: 'Connections' }] : [])];
 const sourceMarkdown = tab !== 'markdown' && data.editorJSON?.type === 'doc' ? documentMarkdown(data.editorJSON) : content;
 return <DocumentNavigation.Provider value={id => void openReference(id)}><Modal title="Your library" onClose={() => void close()} wide footer={<><span className="save-status">{accessSaving ? 'Updating access…' : busy ? 'Saving…' : canEdit ? saved : access ? `${access.permission === 'comment' ? 'Comment' : 'View'} access` : 'Checking access…'}</span><Button disabled={accessSaving} onClick={() => void close()}>Done</Button></>}>
  {accessError && <ErrorNotice onRetry={() => void refreshAccess().catch(e => setAccessError(e.message))}>{accessError}</ErrorNotice>}
  {recoveryError && <ErrorNotice>{recoveryError}</ErrorNotice>}
  {recoveryConflict && <div className="document-recovery"><ErrorNotice>Your unsaved draft was recovered, but the saved item has a newer version. Review the saved copy before choosing which version to keep.</ErrorNotice><details><summary>Review the saved copy</summary><strong>{entity.title}</strong><p>{entity.tags.join(' · ')}</p><textarea aria-label="Latest saved item content" readOnly value={entity.content} rows={8} /></details><div><Button onClick={() => { recoveryBlocked.current = false; setRecoveryConflict(false); version.current = entity.version; void saveRef.current(); }}>Use recovered draft</Button><Button onClick={() => applyEntity(entity)}>Use saved item</Button></div></div>}

  {!access ? !accessError && <Loading label="Checking item access…" /> : <div className="document-layout">
   <div className="document-main">
    <div className="document-meta"><Badge>{data.type || entity.kind}</Badge><span>{new Date(entity.createdAt).toLocaleDateString(undefined, { month: 'long', day: 'numeric', year: 'numeric' })}</span><div className="spacer" /><IconButton label="Share item" onClick={() => void loadExtra('share')}><Share2 size={16} /></IconButton><IconButton label="Version history" onClick={() => void loadExtra('history')}><History size={16} /></IconButton><IconButton label="Comments" onClick={() => void loadExtra('comments')}><MessageSquare size={16} /></IconButton>{canCreate && <IconButton label="Duplicate item" onClick={() => void app.run(async () => { if (!await saveRef.current()) throw new Error('Save this draft successfully before duplicating it.'); const r = await post(`/entities/${entity.id}/duplicate`); app.put(r.entity); }, 'Created a copy')}><Copy size={15} /></IconButton>}</div>
    <fieldset className="editor-fields" disabled={accessSaving}>
     <input className="document-title" aria-label="Document title" readOnly={!canEdit} value={title} onChange={e => setTitle(e.target.value)} placeholder="Untitled note" />
     {canEdit ? <TagsInput value={tags} onChange={setTags} /> : <div className="read-only-tags">{tags.map(tag => <Badge key={tag}>{tag}</Badge>)}</div>}
     {safeUrl(data.url) && <a className="source-url" href={safeUrl(data.url)} target="_blank" rel="noopener noreferrer"><LinkIcon size={14} /><span>{data.url}</span><ArrowUpRight size={14} /></a>}
     {data.type === 'highlight' && data.sourceId && <Button className="source-passage-link" onClick={() => void openSourcePassage()}><BookOpen size={14} />Open source passage</Button>}
     <div className="document-tabs"><Tabs value={canEdit ? tab : 'read'} onChange={next => { if (next === 'markdown' && data.editorJSON?.type === 'doc') setContent(documentMarkdown(data.editorJSON)); setTab(next); }} items={tabItems} /></div>
     {tab === 'write' && canEdit && !isFile && <DocumentEditor id={entity.id} content={content} html={data.html} editorJSON={data.editorJSON} editable={!accessSaving} onOpen={id => void openReference(id)} onChange={next => { setContent(next.content); setData(previous => ({ ...previous, html: next.html, editorJSON: next.editorJSON, entityLinks: next.entityLinks })); }} />}
     {(tab === 'read' || !canEdit) && <><Reader entity={{ ...entity, title, content, data, tags }} reading={reading} canCreate={canCreate} original={isFile ? <FilePreview entity={entity} /> : undefined} />{isFile && /^(audio|video)\//.test(data.mime || data.mimeType || '') && canEdit && canCreate && <Button disabled={accessSaving} onClick={() => void app.run(() => withSavedItem(async () => { const r = await post(`/ai/transcribe/${entity.id}`); applyEntity(r.entity); }), 'Transcript added')}><Video size={15} />Transcribe media</Button>}</>}
     {tab === 'markdown' && canEdit && !isFile && <textarea className="markdown-editor" aria-label="Markdown source" value={content} onChange={event => { const next = documentChange(markdownDocument(event.target.value)); setContent(event.target.value); setData(previous => ({ ...previous, html: next.html, editorJSON: next.editorJSON, entityLinks: next.entityLinks })); }} />}
     {tab === 'related' && canEdit && <><SourcePicker label="Linked items" value={data.connections || []} onChange={ids => setData(d => ({ ...d, connections: ids }))} /><p className="field-hint">Keep useful connections alongside this note. Changes save automatically.</p></>}
    </fieldset>
    <Backlinks id={entity.id} onOpen={id => void openReference(id)} />
    <div className="document-bottom"><Button tone="ghost" onClick={() => saveBlob(new Blob([`# ${title}\n\n${sourceMarkdown}`], { type: 'text/markdown' }), `${title || 'note'}.md`)}><Download size={15} />Export markdown</Button><div className="spacer" />{canEdit && <Button tone="danger" disabled={accessSaving} onClick={() => void app.run(() => app.remove(entity.id))}><Trash2 size={14} />Move to trash</Button>}</div>
   </div>
   {extra && <aside className={`document-aside ${extra === 'share' ? 'sharing-aside' : ''}`}>
    <div className="aside-panel-heading"><h3>{extra === 'history' ? 'Version history' : extra === 'comments' ? 'Conversation' : 'Share this item'}</h3><IconButton label="Close item panel" onClick={() => setExtra(null)}><X size={14} /></IconButton></div>
    {extra === 'comments' && <><div className="comments">{records.map(c => <div className="comment" key={c.id}><strong>{c.authorName || c.userName || 'Workspace member'}</strong><small>{timeAgo(c.createdAt || new Date().toISOString())}</small><p>{c.content}</p>{canComment && (c.userId === app.session.user.id || ['owner', 'admin'].includes(app.workspace.role)) && <button onClick={() => void app.run(async () => { await api(`/comments/${c.id}`, { method: 'DELETE' }); setRecords(records.filter(r => r.id !== c.id)); })}>Remove</button>}</div>)}{!records.length && <p className="muted small">No comments yet.</p>}</div>{canComment ? <form onSubmit={e => { e.preventDefault(); void app.run(async () => { await post(`/entities/${entity.id}/comments`, { content: comment }); setComment(''); const r = await api(`/entities/${entity.id}/comments`); setRecords(r.comments || []); }); }}><textarea aria-label="New comment" required rows={3} value={comment} onChange={e => setComment(e.target.value)} placeholder="Add a comment…" /><Button type="submit" tone="primary">Comment</Button></form> : <p className="field-hint">You have view access. Ask the item owner for permission to comment.</p>}</>}
    {extra === 'history' && <div className="history-list">{records.map(r => <div key={r.version}><div><strong>Version {r.version}</strong><small>{new Date(r.createdAt || r.created_at).toLocaleString()}</small></div>{canEdit && <Button disabled={accessSaving} onClick={() => void app.run(() => withSavedItem(async () => { const v = await post(`/entities/${entity.id}/history/${r.version}/restore`); applyEntity(v.entity); }), 'Version restored')}>Restore</Button>}</div>)}{!records.length && <p className="muted">No previous versions yet.</p>}</div>}
    {extra === 'share' && <ItemSharePanel entity={entity} access={access} refreshAccess={refreshAccess} changeVisibility={changeVisibility} withSavedItem={withSavedItem} />}
   </aside>}
  </div>}
 </Modal></DocumentNavigation.Provider>;
}
export function ItemSharePanel({ entity, access, refreshAccess, changeVisibility, withSavedItem }: {
 entity: Entity; access: ItemAccess; refreshAccess: () => Promise<ItemAccess>;
 changeVisibility: (visibility: ItemAccess['visibility']) => Promise<void>; withSavedItem: (action: () => Promise<void>) => Promise<void>;
}) {
 const app = useWorkspace();
 const [visibility, setVisibility] = useState(access.visibility), [email, setEmail] = useState(''), [permission, setPermission] = useState<'view' | 'comment' | 'edit'>('view');
 const [invite, setInvite] = useState<{ url: string; email: string; days: number } | null>(null), [shareUrl, setShareUrl] = useState('');
 const [allowDuplicate, setAllowDuplicate] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState(''), [publicMessage, setPublicMessage] = useState('');
 const manage = access.permission === 'manage';
 useEffect(() => { setVisibility(access.visibility); }, [access.visibility]);
 async function action(fn: () => Promise<void>) { if (busy) return; setBusy(true); setError(''); try { await withSavedItem(fn); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
 return <div className="item-share-panel">
  <div className="access-summary"><Badge>{access.visibility === 'private' ? <LockKeyhole size={11} /> : <Users size={11} />}{access.visibility === 'private' ? 'Private item' : 'Workspace item'}</Badge><span>Your access: {access.permission}</span></div>
  {error && <ErrorNotice>{error}</ErrorNotice>}
  {manage ? <>
   <form className="form-stack" onSubmit={e => { e.preventDefault(); void action(() => changeVisibility(visibility)); }}>
    <Field label="Item visibility"><select aria-label="Item visibility" value={visibility} disabled={busy} onChange={e => setVisibility(e.target.value as ItemAccess['visibility'])}><option value="workspace">Workspace members</option><option value="private">Private · invited people</option></select></Field>
    <p className="field-hint">Private items are accessible to their owner and invited collaborators. Parent item permissions can also grant access.</p>
    <Button type="submit" busy={busy} disabled={visibility === access.visibility}>Save visibility</Button>
   </form>
   <section className="access-section"><h4>People with direct access</h4><div className="access-person"><div><strong>{access.createdBy === app.session.user.id ? 'You' : 'Item owner'}</strong><small>Owner access</small></div><Badge>Manage</Badge></div>
    {access.grants.map(g => <div className="access-person" key={g.userId}><div><strong>{g.name || g.email}</strong><small>{g.email}</small></div><Badge>{g.permission}</Badge><IconButton label={`Remove direct access for ${g.email}`} disabled={busy} onClick={() => void action(async () => { await api(`/entities/${entity.id}/access/${g.userId}`, { method: 'DELETE' }); await refreshAccess(); app.notify('Direct access removed'); })}><Trash2 size={13} /></IconButton></div>)}
    <p className="field-hint">Workspace members may still have access when visibility is set to Workspace members.</p>
   </section>
   <form className="form-stack access-section" onSubmit={e => { e.preventDefault(); void action(async () => { const result = await post(`/entities/${entity.id}/invite`, { email: email.trim(), permission }); setInvite({ url: result.url, email: email.trim(), days: result.expiresInDays || 7 }); setEmail(''); await refreshAccess(); }); }}>
    <h4>Invite to this item</h4><Field label="Invitee email"><Input aria-label="Invitee email" type="email" required maxLength={254} value={email} disabled={busy} onChange={e => setEmail(e.target.value)} placeholder="person@example.com" /></Field>
    <Field label="Item permission"><select aria-label="Item permission" value={permission} disabled={busy} onChange={e => setPermission(e.target.value as typeof permission)}><option value="view">View · read this item</option><option value="comment">Comment · read and discuss</option><option value="edit">Edit · update this item</option></select></Field>
    <Button type="submit" tone="primary" busy={busy}><Plus size={14} />Create item invitation</Button>
   </form>
   {invite && <div className="invite-result"><strong>Invitation for {invite.email}</strong><p className="field-hint">Copy and share this link directly. It expires in {invite.days} days. No email was sent.</p><Input aria-label="Item invitation link" value={invite.url} readOnly /><Button onClick={() => void app.run(() => navigator.clipboard.writeText(invite.url), 'Invitation copied')}><Copy size={13} />Copy item invitation</Button></div>}
   {access.invitations.length > 0 && <section className="access-section"><h4>Pending invitations</h4>{access.invitations.map(i => <div className="access-person" key={i.id}><div><strong>{i.email}</strong><small>{i.permission} · Expires {new Date(i.expiresAt).toLocaleDateString()}</small></div><IconButton label={`Revoke item invitation for ${i.email}`} disabled={busy} onClick={() => void action(async () => { await api(`/entities/${entity.id}/invitations/${i.id}`, { method: 'DELETE' }); await refreshAccess(); if (invite?.email.toLowerCase() === i.email.toLowerCase()) setInvite(null); app.notify('Invitation revoked'); })}><Trash2 size={13} /></IconButton></div>)}</section>}
   {app.workspace.role !== 'viewer' && <section className="access-section public-access"><h4><Globe size={13} />Public link</h4><p className="field-hint">Anyone with an enabled link can view this item without signing in. Changing visibility to Private does not revoke an existing public link.</p><label className="checkbox-label"><input type="checkbox" checked={allowDuplicate} disabled={busy} onChange={e => setAllowDuplicate(e.target.checked)} />Allow visitors to make a copy</label><Button disabled={busy} onClick={() => void action(async () => { const r = await post(`/entities/${entity.id}/share`, { enabled: true, allowDuplicate }); setShareUrl(r.url); setPublicMessage('Public link enabled'); })}><Share2 size={13} />Enable public link</Button>{shareUrl && <><Input aria-label="Public item link" readOnly value={shareUrl} /><Button onClick={() => void app.run(() => navigator.clipboard.writeText(shareUrl), 'Public link copied')}><Copy size={13} />Copy public link</Button></>}<Button disabled={busy} onClick={() => void action(async () => { await post(`/entities/${entity.id}/share`, { enabled: false }); setShareUrl(''); setPublicMessage('Public link revoked'); })}>Revoke public link</Button>{publicMessage && <p className="field-hint" role="status">{publicMessage}</p>}</section>}
  </> : <p className="field-hint">You can {access.permission === 'view' ? 'read' : access.permission === 'comment' ? 'read and comment on' : 'edit'} this item. Its owner manages visibility and invitations.</p>}
 </div>;
}
