import { useEffect, useRef, useState, type ReactNode, type ButtonHTMLAttributes, type InputHTMLAttributes } from 'react';
import { X, Loader2, ArrowUpRight, Leaf, Check, AlertCircle, Search, Plus } from 'lucide-react';
export function Button({ children, tone = 'default', busy, className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { tone?: 'default' | 'primary' | 'ghost' | 'danger'; busy?: boolean }) { return <button type="button" className={`button ${tone} ${className}`} {...props} disabled={props.disabled || busy}>{busy && <Loader2 size={15} className="spin" />}{children}</button>; }
export function IconButton({ label, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { label: string }) { return <button type="button" className={`icon-button ${props.className || ''}`} {...props} title={label} aria-label={label}>{children}</button>; }
export function Badge({ children, tone = '' }: { children: ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span>; }
export function Field({ label, hint, children }: { label: string; hint?: string; children: ReactNode }) { return <label className="field"><span className="field-label">{label}</span>{children}{hint && <span className="field-hint">{hint}</span>}</label>; }
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={`input ${props.className || ''}`} />; }
export function Modal({ title, children, onClose, wide = false, footer }: { title: string; children: ReactNode; onClose: () => void; wide?: boolean; footer?: ReactNode }) {
 const ref = useRef<HTMLDivElement>(null); const close = useRef(onClose); close.current = onClose;
 useEffect(() => { const prior = document.activeElement as HTMLElement; const oldOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; const focus = setTimeout(() => ref.current?.querySelector<HTMLElement>('input, textarea, select, button, [tabindex="0"]')?.focus(), 40); const key = (e: KeyboardEvent) => { const top = [...document.querySelectorAll<HTMLElement>('[role=dialog][aria-modal=true]')].filter(element => element.getClientRects().length).at(-1); if (top !== ref.current) return; if (e.key === 'Escape') close.current(); if (e.key !== 'Tab') return; const items = [...(ref.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),textarea,select,a[href],[tabindex="0"]') || [])].filter(el => el.getClientRects().length); if (!items.length) return; const first = items[0], last = items[items.length - 1]; if (e.shiftKey && document.activeElement === first) { e.preventDefault(); last.focus(); } else if (!e.shiftKey && document.activeElement === last) { e.preventDefault(); first.focus(); } }; window.addEventListener('keydown', key); return () => { clearTimeout(focus); document.body.style.overflow = oldOverflow; window.removeEventListener('keydown', key); prior?.focus(); }; }, []);
 return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) onClose(); }}><div ref={ref} role="dialog" aria-modal="true" aria-label={title} className={`modal ${wide ? 'wide' : ''}`}><header className="modal-header"><h2>{title}</h2><IconButton label="Close dialog" onClick={onClose}><X size={18} /></IconButton></header><div className="modal-content">{children}</div>{footer && <footer className="modal-footer">{footer}</footer>}</div></div>;
}
export function PageHeader({ eyebrow, title, description, children }: { eyebrow?: string; title: string; description?: string; children?: ReactNode }) { return <header className="page-header"><div>{eyebrow && <div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description && <p>{description}</p>}</div>{children && <div className="header-actions">{children}</div>}</header>; }
export function Empty({ icon = <Leaf size={26} />, title, description, action }: { icon?: ReactNode; title: string; description: string; action?: ReactNode }) { return <div className="empty-state"><div className="empty-icon">{icon}</div><h3>{title}</h3><p>{description}</p>{action}</div>; }
export function Loading({ label = 'Opening your workspace…' }: { label?: string }) { return <div className="loading"><Loader2 className="spin" size={23} /><p>{label}</p></div>; }
export function ErrorNotice({ children, onRetry }: { children: ReactNode; onRetry?: () => void }) { return <div className="error-notice" role="alert"><AlertCircle size={18} /><span>{children}</span>{onRetry && <Button onClick={onRetry}>Try again</Button>}</div>; }
export function Tabs({ items, value, onChange }: { items: { id: string; label: string; icon?: ReactNode; count?: number }[]; value: string; onChange: (id: string) => void }) { return <div className="tabs" role="tablist">{items.map(t => <button type="button" key={t.id} role="tab" aria-selected={value === t.id} className={value === t.id ? 'active' : ''} onClick={() => onChange(t.id)}>{t.icon}{t.label}{t.count !== undefined && <span>{t.count}</span>}</button>)}</div>; }
export function SearchBox({ value, onChange, placeholder = 'Search…' }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <div className="search-box"><Search size={16} /><input aria-label={placeholder} value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder} />{value && <IconButton label="Clear search" onClick={() => onChange('')}><X size={14} /></IconButton>}</div>; }
export function ExternalLink({ href, children }: { href: string; children: ReactNode }) { return <a className="text-link" href={href} target="_blank" rel="noopener noreferrer">{children}<ArrowUpRight size={13} /></a>; }
export function TagsInput({ value, onChange }: { value: string[]; onChange: (tags: string[]) => void }) { const [text, setText] = useState(''); return <div className="tags-input">{value.map(t => <button type="button" key={t} onClick={() => onChange(value.filter(v => v !== t))}>{t}<X size={12} /></button>)}<input aria-label="Add tags" placeholder="Add a tag…" value={text} onChange={e => setText(e.target.value)} onKeyDown={e => { if (['Enter', ','].includes(e.key)) { e.preventDefault(); const v = text.trim().replace(/,$/, ''); if (v && !value.includes(v)) onChange([...value, v]); setText(''); } }} onBlur={() => { if (text.trim() && !value.includes(text.trim())) onChange([...value, text.trim()]); setText(''); }} /></div>; }
export function ChoiceChips({ options, value, onChange }: { options: string[]; value: string[]; onChange: (v: string[]) => void }) { return <div className="choice-chips">{options.map(o => <button type="button" key={o} className={value.includes(o) ? 'selected' : ''} onClick={() => onChange(value.includes(o) ? value.filter(v => v !== o) : [...value, o])}>{value.includes(o) ? <Check size={12} /> : <Plus size={12} />}{o}</button>)}</div>; }
export const platforms = ['X', 'LinkedIn', 'Instagram', 'Threads', 'TikTok', 'YouTube', 'Facebook', 'Substack'];
export const timeAgo = (date: string) => { const d = Date.now() - new Date(date).getTime(); return d < 60000 ? 'Just now' : d < 3600000 ? `${Math.floor(d / 60000)}m ago` : d < 86400000 ? `${Math.floor(d / 3600000)}h ago` : new Date(date).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }); };
export const number = (v: number | undefined) => v === undefined || v === null ? '—' : Intl.NumberFormat(undefined, { notation: 'compact', maximumFractionDigits: 1 }).format(v);
